.base:
  image: node:18
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_JOB_STAGE == "publish"'
      when: manual
      allow_failure: true
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
  - code
  - build
  - validate
  - publish

lint:
  extends: .base
  stage: code
  script:
    - yarn lint

style:
  extends: .base
  stage: code
  script:
    - yarn check

build:
  extends: .base
  stage: build
  needs:
    - lint
    - style
  script:
    - yarn repo build
  artifacts: 
    paths:
      - build/

validate:
  extends: .base
  stage: validate
  needs:
    - build
  script:
    - yarn repo publish -t $PUBLISH_NPM_TOKEN --dry

publish:
  extends: .base
  stage: publish
  needs:
    - build
    - validate
  script:
    - yarn repo publish -t $PUBLISH_NPM_TOKEN
