enableScripts: false

enableTelemetry: false

initScope: klnjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

npmScopes: 
  klnjs:
    npmRegistryServer: //npm.pkg.github.com
    
yarnPath: .yarn/releases/yarn-3.4.1.cjs
