name: code

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job:
    name: ${{ matrix.script }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: ["test", "lint", "format"]
    env:
      BUN_ENV: production
      FORCE_COLOR: 1
      TURBO_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Tools
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2

      - name: Cache
        uses: rharkor/caching-for-turbo@439abec0d28d21b192fa8817b744ffdf1ee5ac0d # v1.5

      - name: Install
        run: bun install

      - name: Run ${{ matrix.script }}
        run: bun run ${{ matrix.script }}
