name: Code

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        script: ["test", "eslint", "prettier"]
    env:
      BUN_ENV: production
      FORCE_COLOR: 1
      TURBO_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      
      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache      
        uses: dtinth/setup-github-actions-caching-for-turbo@a0e976d970c2a94366a26984efcef3030e2c0115 # v1.2.0

      - name: Install
        run: bun install

      - name: Run ${{ matrix.script }}
        run: bun run ${{ matrix.script }}


