name: Code

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: ["test", "eslint", "prettier"]
    env:
      BUN_ENV: production
      FORCE_COLOR: 1
      TURBO_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Tools
        uses: asdf-vm/actions/install@v3

      - name: Cache
        uses: dtinth/setup-github-actions-caching-for-turbo@cc723b4600e40a6b8815b65701d8614b91e2669e # v1.3.0

      - name: Install
        run: bun install

      - name: Run ${{ matrix.script }}
        run: bun run ${{ matrix.script }}
