name: Code

on:
  pull_request:
    branches:
      - master

jobs:
#  typing:
#    name: Typing
#    needs: install
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Run TypeScript
#        run: npm run type

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Linter
        run: yarn run lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Prettier
        run: yarn run code

  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run verify
        run: yarn run verify
