name: pull request

on:
  pull_request:
    branches:
      - master

jobs:
  eslint:
    uses: ./.github/workflows/run_eslint.yml

  prettier:
    uses: ./.github/workflows/run_prettier.yml

  verify:
    uses: ./.github/workflows/run_verify.yml
