name: verify

on: workflow_call

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: verify
        run: yarn run verify
