name: on master pr

on:
  pull_request:
    branches:
      - master

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  eslint:
    uses: ./.github/workflows/job_eslint.yml

  prettier:
    uses: ./.github/workflows/job_prettier.yml

  verify:
    uses: ./.github/workflows/job_verify.yml
