name: pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        script: ["test", "eslint", "prettier"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup
        uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install

      - name: Execute ${{ matrix.script }}
        run: bun run ${{ matrix.script }}
        
  publish: 
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '🤖') }}
    needs: [code]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: oven-sh/setup-bun@v1

      - name: Publish Dry
        if: ${{ !contains(github.ref, 'master') }}
        run: npm publish --workspaces --access=public --dry-run

      - name: Publish
        if: ${{ contains(github.ref, 'master') && !contains(github.event.head_commit.message, '🤖') }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --workspaces --access=public


