name: pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  code:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        script: ["verify", "eslint", "prettier"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Execute ${{ matrix.script }}
        run: pnpm run ${{ matrix.script }}
        
  publish: 
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master') && !contains(github.event.head_commit.message, '🤖')
    needs: [code]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Publish 
        run: pnpm run publish
