name: Publish

on:
  push:
    branches:
      - master

env:
  BUN_ENV: production
  FORCE_COLOR: 1
  TURBO_TELEMETRY_DISABLED: 1

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc

      - name: License
        run: find packages/*/* -maxdepth 0 -type d -exec cp LICENSE {} \;

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --workspaces --provenance --access=public
