name: Publish

on:
  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish: 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      FORCE_COLOR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc

      - name: License
        run: find packages/*/* -maxdepth 0 -type d -exec cp LICENSE {} \;

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --workspaces --provenance --access=public
